export const ErrorCodes = {
  VALIDATION_ERROR:       'VALIDATION_ERROR',
  AUTH_INVALID_OTP:       'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED:       'AUTH_OTP_EXPIRED',
  AUTH_OTP_RATE_LIMITED:  'AUTH_OTP_RATE_LIMITED',
  AUTH_MISSING_TOKEN:     'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN:     'AUTH_INVALID_TOKEN',
  AUTH_FORBIDDEN:         'AUTH_FORBIDDEN',
  CONFLICT:              'CONFLICT',
  NOT_FOUND:             'NOT_FOUND',
  INTERNAL_ERROR:        'INTERNAL_ERROR',
  MESS_NOT_FOUND:      'MESS_NOT_FOUND',
  MESS_NOT_ACTIVE:     'MESS_NOT_ACTIVE',
  MESS_OWNER_MISMATCH: 'MESS_OWNER_MISMATCH',
  PLAN_NOT_FOUND:      'PLAN_NOT_FOUND',
  SUB_NOT_FOUND:               'SUB_NOT_FOUND',
  SUB_ALREADY_ACTIVE:          'SUB_ALREADY_ACTIVE',
  SUB_NOT_ACTIVE:              'SUB_NOT_ACTIVE',
  MEAL_SLOT_NOT_FOUND:         'MEAL_SLOT_NOT_FOUND',
  MEAL_SLOT_ALREADY_CANCELLED: 'MEAL_SLOT_ALREADY_CANCELLED',
  MEAL_SLOT_WINDOW_EXPIRED:    'MEAL_SLOT_WINDOW_EXPIRED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
